### ISSUE TITLE
Error in Launch files

### ISSUE THREAD

**Issue by srikrishna3118** [OPT4SMART/ChoiRbot#1]
I have forked the project and added a dockerized version of the instance. 
Here : https://github.com/srikrishna3118/ChoiRbot

when running ros2 launch choirbot_examples containment.launch.py -n 6
There is some weird error saying [ERROR] [launch]: Caught exception in launch (see debug for traceback): I/O operation on closed file

**Comment by andreacamisa** [comment]
What OS are you using? What version of ROS 2? Did you try to launch it on a non-dockerized instance? Please paste here the traceback of the error.

**Comment by srikrishna3118** [comment]
Thank you for your response, we have fixed the issue regarding the dependency. can we raise a PR for the same to add the same adding Dockerfile 
https://github.com/srikrishna3118/ChoiRbot/blob/master/Dockerfile

https://github.com/srikrishna3118/ChoiRbot
we have updated the readme and added Dockerfile and docker compose file to run the container with host support.

**Comment by andreacamisa** [comment]
Sure, thank you!
