### ISSUE TITLE
[ROS2] Turtlebot3 Spawn - unresolved issue 

### ISSUE THREAD

**Issue by dhollosi** [OPT4SMART/ChoiRbot#3]
Hi,

Firstly, thank you for this very helpful repository! It (almost) works flawlessly which in my experience is rare. I plan on adding some other task assignment mathematical models (such as the hungarian algorithm for instance). 

I just had a minor issue when running the taskassignment example: the turtlebot3 is not showing up in the gazebo simulation environment. When I run the examples, I can see the Center of Mass of the robots and other properties, and see that they are moving, but I am unable to actually visualise the burger models (sdf model). 

I have spent a few hours trying to get this to work but to no avail. I was therefore wondering if anyone else had encountered this issue, and if they'd be willing to share any tips. I have followed all the installation instructions and even re-installed everything. I have of course used the colcon builder and sourced the respective setup.bash files prior to running the example. I am fairly new to ROS2, so maybe I have missed something.

Thanks in advance,

**Comment by andrea-testa** [comment]
Hi, thank you for your interest in our project and for the positive comments! 
Assuming that you installed the turlebot3 files in the turtlebot3_ws folder as suggested on the robot website, you should add in your .bashrc the following lines
export TURTLEBOT3_MODEL=burger
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:~/turtlebot3_ws/src/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models
You should check that the path exists and adjust it accordingly. If you installed the packages via apt install, they should be located instead in /opt/ros/dashing/share/turtlebot3_gazebo/models.
Let us know if this solved the problem :)

**Comment by dhollosi** [comment]
Thanks for your prompt answer! Yes I have already done that, and after double checking  everything can't figure out where the error lies... I have attached a screenshot of the current situation. The process I run is the following:

Terminal 1: 
sourcing ROS2 and 
colcon build in ChoirBot directory. I get this minor issue : Summary: 4 packages finished [8.15s]
 ` 3 packages had stderr output: choirbot choirbot_examples my-test-package. `. So a mostly successful build.
colcon build in turtlebot3_ws directory

Terminal 2: 
sourcing ROS2, and source install/local_setup.bash in ChoirBot directory. Then in ChoirBot/src/
 ` ros2 launch choirbot_examples taskassignment.launch.py`

Hope my working logic is clear.


![gazebo_no_tb3](https://user-images.githubusercontent.com/66771140/162488560-8c650980-00c0-4fad-9112-6e23e2bd8bcb.png)

**Comment by andrea-testa** [comment]
I got this problem sometimes too, it was related to the fact that the directory path was not correct. Which files do you see if you run an 'ls' on ~/turtlebot3_ws/src/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models?

**Comment by dhollosi** [comment]
Brilliant, problem is fixed! It was indeed a directory issue.. Thanks :)

**Comment by andrea-testa** [comment]
You're welcome!
